# Generated by Django 5.2.16 on 2026-09-07 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0070_alter_kyc_pm_actionnaire_alter_kyc_pm_mandataire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tauxevolution',
            name='taux',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
