# Generated by Django 5.2.16 on 2026-09-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0071_alter_tauxevolution_taux'),
    ]

    operations = [
        migrations.AddField(
            model_name='appreciation_globale',
            name='methode_taux',
            field=models.CharField(blank=True, default='flux', max_length=5, verbose_name='Méthode retenue (flux / stock)'),
        ),
        migrations.AddField(
            model_name='appreciationconfig',
            name='methode_taux',
            field=models.CharField(choices=[('flux', 'Flux (nouveaux clients / évolution récente)'), ('stock', 'Stock (toute la base)')], default='flux', help_text="Détermine si l'appréciation globale s'appuie sur les taux « flux » ou « stock » : taux d'évolution, taux de qualité agent et notation retenue.", max_length=5, verbose_name='Méthode de calcul des taux'),
        ),
        migrations.AlterField(
            model_name='appreciation_globale',
            name='taux_evolution',
            field=models.FloatField(blank=True, null=True, verbose_name="Taux d'évolution (moy. PP+PM)"),
        ),
    ]
